[package]
name = "msuk-helper-collection"
version = "0.1.0"
edition = "2024"
authors = ["Markku Sukanen <markku.sukanen@gmail.com>"]
license = "MIT OR Apache-2.0"
maintainer = { status = "experimental" }

[dependencies]
